version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - .:/app
    restart: unless-stopped